QLD Open Data Sprint 1
qld-gov-au/ckanext-data-qld pull request #105
Opened 2021-09-18 15:39 UTC by MarkCalvert

Hi @duttonw & @ThrawnCA ,

This PR includes the following stories from sprint 1:
- [1. Record in the dataset metadata that the dataset includes de identified data](https://salsadigital.atlassian.net/browse/DQL3-1)
- [2. Add Re-identification risk governance acknowledgement to dataset metadata](https://salsadigital.atlassian.net/browse/DQL3-2)
- [4. Enable dataset currency email notifications](https://salsadigital.atlassian.net/browse/DQL3-4)
- [5. Create Report – Admin report](https://salsadigital.atlassian.net/browse/DQL3-5)
- [6. Populate Admin report with De-identified Datasets metric](https://salsadigital.atlassian.net/browse/DQL3-6)
- [7. Populate Admin Report with Dataset Currency metric](https://salsadigital.atlassian.net/browse/DQL3-7)

Sorry this is such a big PR! But they needed to be all together because the stories depend on each other and our QA process took so long all the code ended up together.
For future PR the stories are smaller and not dependent on each other so we can do more regular small PRs.

The only CKAN configuration is this:
```
# ckanext-data-qld Resource Freshness
ckanext.resource_freshness.update_frequencies = { "monthly": 30, "quarterly": 91, "half-yearly": 182, "annually": 365}
```
If this config value is not set the code will default to using a hardcoded list of the same values here https://github.com/salsadigitalauorg/ckanext-data-qld/blob/develop/ckanext/data_qld/resource_freshness/helpers/helpers.py#L13

For the automation tests to all pass successfully the ckanext-data-qld-theme PR will need to be merged

Happy to tee up a meeting next week to go over any questions with this PR.

2021-09-21 00:59 UTC, duttonw approved these changes

2021-09-23 01:05 UTC, ThrawnCA requested changes
This is too big too properly review in one pull request; it would have been better to have reviewed it incrementally.

2021-09-23 01:05 UTC, ThrawnCA commented on test/features/admin_reporting.feature
> +    Scenario: As an admin user of my organisation, I can view 'My Reports' tab in the dashboard and show the "Admin Report" with filters and table columns
Scenario names should not include double quotes, as they interfere with taking screenshots.

2021-09-23 01:05 UTC, ThrawnCA commented on test/features/admin_reporting.feature
> +    Scenario: As an admin user of my organisation, when I view my admin report, I can verify the de-indentified datasets row exists
Misspelled "de-identified"

2021-09-23 01:05 UTC, ThrawnCA commented on test/features/admin_reporting.feature
> +    Scenario: As an admin user of my organisation, when I view my admin report, I can verify the over due datasets row exists correct
"overdue" should be one word.

2021-09-24 03:37 UTC, merged