CHDEXCHAE workpackage
qld-gov-au/ckanext-data-qld pull request #181
Opened 2022-11-11 02:19 UTC by duttonw

2022-11-28 01:28 UTC, ThrawnCA commented on .docker/test.ini
> +who.config_file = /srv/app/who.ini
I would prefer to leave this as a variable, rather than relying on the Docker container path.

2023-02-16 00:16 UTC, ThrawnCA reviewed
This is cluttered with literally hundreds of "changes" that are just splitting code over two lines to avoid going over a maximum line length, or similar refactoring like replacing function imports with module imports.

It's not necessary, it's arguably not even an improvement (just a different style, with both strengths and weaknesses), it makes actual code review much harder, and it's not what Link Digital is being paid for.

2023-02-16 00:16 UTC, ThrawnCA commented on Makefile
> +###############################################################################
As previously discussed, a Makefile is a very poor approach to dependency installation when `pip` is sufficient for the job, is the standard Python tool on all platforms, and is already configured in this repository.

2023-02-16 01:02 UTC, ThrawnCA requested changes

2023-02-16 01:02 UTC, ThrawnCA commented on ckanext/data_qld/validation.py
> +        default_schema = json.loads(default_schema) if isinstance(
This "parse as JSON else default" behaviour is used enough times that it should probably be extracted to a helper function.

2023-02-16 01:02 UTC, ThrawnCA commented on .docker/scripts/init-ext.sh
> +install_requirements . extensions
This doesn't match usual naming conventions at all. Why was it changed?

2023-03-08 23:19 UTC, duttonw commented
OpenData Team have accepted the business risk. Yes there is things in there we would like done differently as it is causing tech debt, overall it is still in better shape than last year. (except for the need for a test plugin shim that is interacted by test fixtures reading 'tags')

2023-03-08 23:23 UTC, merged